### Product Index

GET http://localhost:3000/products.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Nzg4MzgwMDV9.5DeKg3Zy89IV7URWCBMGM0awKVP40cm9d7amGaqrgTg

### Product Show
GET http://localhost:3000/products/1

### Product Show
GET http://localhost:3000/products/2

### Product Create
POST http://localhost:3000/products.json
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Nzg4MzgwMDV9.5DeKg3Zy89IV7URWCBMGM0awKVP40cm9d7amGaqrgTg

{"name": "Engine",
"price": 2400,
"description": "Creates small explosions under pistons, to propel a vehicle forwards or backwards by turning mechnical parts",
"supplier_id": 1,
"product_id": 1
}

### Product Update

PATCH http://localhost:3000/products/3.json
Content-Type: application/json

### Product Delete/Destroy

DELETE http://localhost:3000/images/7.json

### Supplier Index

GET http://localhost:3000/suppliers

### Supplier Show

GET http://localhost:3000/suppliers/1

### Supplier Create

POST http://localhost:3000/suppliers/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Nzg4MzgwMDV9.5DeKg3Zy89IV7URWCBMGM0awKVP40cm9d7amGaqrgTg
 
 {
  "name": "mike",
  "supplier_id": 1
  }

### Supplier Update

PATCH http://localhost:3000/suppliers/1.json

### Supplier Delete/Destroy

DELETE http://localhost:3000/suppliers/json

### User Create (aka signup)

POST http://localhost:3000/users.json
Content-Type: application/json

{
"name": "Mike",
"email": "mikefitz@test.com",
"password": "password",
"password_confirmation": "password"
}


### Session Create

POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "mikefitz@test.com",
  "password": "password"
}

### Order Index

GET http://localhost:3000/orders.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Nzg5MjgxNDd9.rV4BIKV5UeM3RELQbq1QLqo_9s9WpideuH0fSJaz7_I

### Order Show

GET http://localhost:3000/orders/1

### Order Create

POST http://localhost:3000/orders.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Nzg5MjgxNDd9.rV4BIKV5UeM3RELQbq1QLqo_9s9WpideuH0fSJaz7_I

{"product_id": 1,
"quantity": 1,
}