@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Nzk0NDQ3OTV9.6HbdiDW0iwlrs-py0-ZF2iTpS9KTXsTn9zeQncTQaBw

### Product Index

GET http://localhost:3000/products.json?category=Exhaust
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Product Show
GET http://localhost:3000/products/1.json?category=Exhaust

### Product Show
GET http://localhost:3000/products/2.json

### Product Create
POST http://localhost:3000/products.json
Content-type: application/json
Authorization: Bearer {{jwt}}

{"name": "Engine",
"price": 2400,
"description": "Creates small explosions under pistons, to propel a vehicle forwards or backwards by turning mechnical parts",
"supplier_id": 1,
"product_id": 1
}

### Product Update

PATCH http://localhost:3000/products/3.json
Content-Type: application/json

### Product Delete/Destroy

DELETE http://localhost:3000/images/7.json

### Supplier Index

GET http://localhost:3000/suppliers

### Supplier Show

GET http://localhost:3000/suppliers/1

### Supplier Create

POST http://localhost:3000/suppliers/
Content-Type: application/json
Authorization: Bearer {{jwt}}
 
 {
  "name": "mike",
  "supplier_id": 1
  }

### Supplier Update

PATCH http://localhost:3000/suppliers/1.json

### Supplier Delete/Destroy

DELETE http://localhost:3000/suppliers/json

### User Create (aka signup)

POST http://localhost:3000/users.json
Content-Type: application/json

{
"name": "Steve",
"email": "Steveharvey@test.com",
"password": "password",
"password_confirmation": "password"
}


### Session Create

POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "mikefitz@test.com",
  "password": "password"
}


### Order Index

GET http://localhost:3000/orders.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Order Show

GET http://localhost:3000/orders/9.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Order Create

POST http://localhost:3000/orders.json
Content-Type: application/json
Authorization: Bearer {{jwt}}



### CartedProduct Create

POST http://localhost:3000/carted_products.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{"product_id": 2,
"order_id": 2,
"quantity": 2,
"status": "carted"
}

### CartedProduct Index

GET http://localhost:3000/carted_products.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Carted Product Destroy
DELETE http://localhost:3000/carted_products/.json
Authorization: Bearer {{jwt}}
