### Product Index

GET http://localhost:3000/products

### Product Show
GET http://localhost:3000/products/1

### Product Show
GET http://localhost:3000/products/2

### Product Create
POST http://localhost:3000/products.json

### Product Update

PATCH http://localhost:3000/products/1.json
Content-Type: application/json 
{
  "name": "ECM"
}

### Product Delete/Destroy

 DELETE http://localhost:3000/products/4.json